backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "kegiatan"
    label: "Kegiatan"
    folder: "contents/kegiatan"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/kegiatan/{{slug}}"
    sort: "date:desc"
    fields:
      - { label: "Judul", name: "title", widget: "string", required: true }
      - {
          label: "Tanggal",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "DD MMMM YYYY",
          time_format: false,
          required: true,
        }
      - { label: "Gambar", name: "image", widget: "image", required: true }
      - { label: "Isi", name: "body", widget: "markdown", required: true }
      
